[Settings]

# All netfliy options should be defined here. UI options should stay empty.

[build]
base = ""
publish = "web/public"

environment = { HUGO_VERSION="0.55.3" }

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(env && make web HUGO=$(which hugo)) || (sleep 30; false)"

[context.deploy-preview]

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(env && make web HUGO=$(which hugo) WEBSITE_BASE_URL=${DEPLOY_PRIME_URL}) || (sleep 30; false)"