[Settings]

# All netfliy options should be defined here. UI options should stay empty.

[build]
base = ""
publish = "web/public"
# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(echo $(which hugo) && env && make web HUGO=$(which hugo)) || (sleep 30; false)"

[build.environment]
HUGO_VERSION = "0.88.0"
GO_VERSION=1.20
GIMME_GO_VERSION=1.20

[context.deploy-preview]

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(echo $(which hugo) && env && make web HUGO=$(which hugo) WEBSITE_BASE_URL=${DEPLOY_PRIME_URL}) || (sleep 30; false)"


