version: 2
jobs:
  website:
    docker:
      # TODO(bwplotka): Just create image with git as well.
      - image: cibuilds/hugo:v0.54.0
    working_directory: ~/website
    steps:
      - run: apk update && apk add git
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            git init
            git config --global user.email "bwplotka@users.noreply.github.com"
            git config --global user.name "Bartek"
            git remote add origin "https://${GITHUB_TOKEN}@github.com/bwplotka/my.git"
            make web-deploy

workflows:
  version: 2
  thanos:
    jobs:
      - hugo:
          filters:
            branches:
              only: master
