version: 2
jobs:
  website:
    docker:
      # TODO(bwplotka): We should definitely
      - image: cibuilds/hugo:v0.54.0
    working_directory: ~/website
    steps:
      - run: apk update && apk add git
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            cd website
            hugo -v
            cd public
            git init
            git config --global user.email "adrien-f@users.noreply.github.com"
            git config --global user.name "AdrienF"
            git add .
            git commit -m "Deploy from CI"
            git push --force --quiet "https://${GITHUB_TOKEN}@github.com/adrien-f/thanos.git" master:gh-pages
workflows:
  version: 2
  thanos:
    jobs:
      - hugo:
          filters:
            branches:
              only: master
