# --- Categories ----

[[filter]]
query = """
list:(thanos-io.googlegroups.com) OR \
list:(prometheus-team.googlegroups.com)
"""
Label = "STARRED"

[[filter]]
query = """
from:(messages-noreply@linkedin.com)
"""
label = "CATEGORY_SOCIAL"

[[filter]]
query = """
from:(naliczenia@patronat.gd.pl) OR \
from:(e-faktura@pl.orange.com) OR invoice
"""
label = "CATEGORY_UPDATES"

[[filter]]
query = "(from:notifications@github.com)"
label = "CATEGORY_FORUMS"

# --- Dev ---

#[[filter]]
#query = """
#from:notifications@github.com \
#-to:team_mention@noreply.github.com \
#-to:mention@noreply.github.com \
#-to:author@noreply.github.com \
#-to:assign@noreply.github.com
#"""
#Archive = true

[[filter]]
query = "(from:me AND to:reply@reply.github.com)"
label = "Dev/Mentions"

[[filter]]
query = """
(-to:team_mention@noreply.github.com \
(from:(notifications@github.com) AND (@bwplotka OR to:mention@noreply.github.com OR to:author@noreply.github.com OR to:assign@noreply.github.com)))
"""
label = "Dev/Mentions"

[[filter]]
query = """
cc:(ci_activity@noreply.github.com) OR \
from:(builds@travis-ci.org) OR \
from:(builds@circleci.com)
"""
Archive = true
label = "Dev/CIs"

# ): Too spammy.
[[filter]]
query = """
list:(openshift.github.com) \
-to:mention@noreply.github.com \
-to:author@noreply.github.com \
-to:assign@noreply.github.com
"""
Archive = true
label = "Dev/LessImportant"

# --- Projects

[[filter]]
query = """
list:(prometheus-london.googlegroups.com) OR \
list:(prometheus-users.googlegroups.com) OR \
list:(prometheus-developers.googlegroups.com)
"""
label = "Dev/Prometheus"

[[filter]]
query = """
list:(thanos-io.googlegroups.com)
"""
label = "Dev/Thanos"

[[filter]]
query = """
subject:(CNCF) OR subject:(cncf)
"""
label = "Dev/CNCF"

# --- Kasia

[[filter]]
query = """
from:(naliczenia@patronat.gd.pl) OR \
from:(bok@jpk.pl) OR \
from:(e-faktura@pl.orange.com)
"""
forwardTo = "kwplotka@gmail.com"
label = "Life"

# --- Not sure...

[[filter]]
query = """
from:Launchpad OR \
reply-to: reviews@mesos.apache.org 
"""
Archive = true
label = "ProbablyGarbage"

# --- Delete ORs ---

[[filter]]
query = """
from:(newsletter@e.citeam.pl) OR \
from:(donosiciel@vwpolo-klub.pl) OR \
from:(rainer.lesani@ashampoo.com) OR \
from:(wordpress@cyrkowakuchnia.pl) OR \
cc:(reviews@mesos.apache.org)
"""
delete = true
